from apps.home_app import HomeApp
from apps.walsh_app import WalshApp
from apps.walsh_app_secure import WalshAppSecure
from apps.login_app import LoginApp
from apps.solar_mach import SolarMach
from apps.spacy_nlp import SpacyNLP
from apps.uber_app import UberNYC
from apps.cheat_app import CheatApp
from apps.myloading_app import MyLoadingApp
from apps.signup import SignUpApp
from apps.cookie_cutter import CookieCutterApp
from apps.load_app import LoaderTestApp
from apps.ricepest_dashboard import RicePestDashboard
from apps.ricepest_data import RicePestDataLayers
from apps.ricepest_import import RicePestImportData
from apps.ricepest_ai import RicePestAIDashboard
from apps.ricepest_config import RicePestConfig
from apps.riceblast_dashboard import RiceBlastDashboard
from apps.riceblast_data import RiceBlastDataLayers
from apps.riceblast_import import RiceBlastImportData
from apps.riceblast_ai import RiceBlastAIDashboard
from apps.disaster_dashboard import DisasterDashboard
from apps.disaster_data import DisasterDataLayers
from apps.disaster_ai import DisasterAIDashboard
from apps.config import config
from apps.ricepest_train import bph_train_model